# Generated by Django 5.1.4 on 2025-01-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_bookstore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookstore",
            name="book",
        ),
        migrations.AddField(
            model_name="book",
            name="store_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_store",
                to="api.bookstore",
            ),
        ),
    ]
