# Generated by Django 5.1.4 on 2025-01-08 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_bookstore_book_book_store_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="store_name",
        ),
        migrations.AddField(
            model_name="bookstore",
            name="book_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book",
                to="api.book",
            ),
        ),
    ]
