# Generated by Django 5.1.4 on 2025-01-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_bookstore_book_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookstore",
            name="book_list",
        ),
        migrations.AddField(
            model_name="bookstore",
            name="book_list",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="book_list", to="api.book"
            ),
        ),
    ]
