# Generated by Django 5.1.4 on 2025-01-08 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_bookstore_book_list_bookstore_book_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookstore",
            name="book_list",
        ),
        migrations.AddField(
            model_name="book",
            name="store_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.bookstore",
            ),
        ),
    ]
