# Generated by Django 5.1.4 on 2025-01-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_order_orderitem_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="store_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_list",
                to="api.bookstore",
            ),
        ),
    ]
