# Generated by Django 5.1.4 on 2025-01-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_book_description_order_orderitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
